# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('paint', 'Paint')], default='photo', max_length=4)),
                ('source', models.CharField(choices=[('original', 'Original'), ('market', 'From Market')], default='original', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('n_copies', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fpath', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
