# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('original', 'Original'), ('market', 'From Market')], default='original', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('paint', 'Paint')], default='photo', max_length=32),
        ),
    ]
