# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170621_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
