# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, default='usd', max_length=16, null=True),
        ),
    ]
