# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('cad', 'CAD'), ('cny', 'CNY')], default='usd', max_length=16),
        ),
    ]
