# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='year',
        ),
    ]
