# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0008_ownerhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('expect_price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('expired', 'Expired'), ('accepted expiry', 'Accepted Expiry')], default='pending', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('expired', 'Expired'), ('accepted expiry', 'Accepted Expiry')], default='pending', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='accepted_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bids.Transaction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
